### ISSUE TITLE
Improve SocialConnect dune dashboard

### ISSUE THREAD

**Issue by arthurgousset** [celo-org/social-connect#204]
Improve dashboards: 
- SocialConnect ([0xarthurxyz/socialconnect](https://dune.com/0xarthurxyz/socialconnect))
- ODIS ([0xarthurxyz/odis](https://dune.com/0xarthurxyz/odis))

```[tasklist]
### Tasks
- [x] Add link to SocialConnect repo
- [x] Update total user counter
- [x] Combine SocialConnect and ODIS dashboards into 1
- [x] Modify charts with {{day, week, month}} switch
- [ ] Add "issuer" filter (out of scope in this revision, maybe later)
- [ ] Add "mapped identifiers by issuer" order descending (out of scope in this revision, maybe later)
```

**Comment by 0xarthurxyz** [comment]
Bumping the prio, here because both Marek and Tim asked about this.

**Comment by arthurgousset** [comment]
Polished the publicly-available dune dashboard for SocialConnect: [dune.com/0xarthurxyz/socialconnect](http://dune.com/0xarthurxyz/socialconnect)
It shows totals across all issuers.

<img width="1488" alt="image" src="https://github.com/celo-org/social-connect/assets/46296830/aca039e7-e680-4193-b921-6330b765bb43">
<img width="1497" alt="image" src="https://github.com/celo-org/social-connect/assets/46296830/06e73f77-d4e2-45a8-be51-e10a827863c6">
