### ISSUE TITLE
OdisPayments Balance Distribution + Signer Compensation

### ISSUE THREAD

**Issue by alecps** [celo-org/social-connect#28]
```[tasklist]
### Tasks
- [ ] https://github.com/celo-org/social-connect/issues/26
- [ ] https://github.com/celo-org/social-connect/issues/25
- [ ] https://github.com/celo-org/social-connect/issues/24
```
