### ISSUE TITLE
Verify SocialConnect ready for Alfajores L2 Migration

### ISSUE THREAD

**Issue by alecps** [celo-org/social-connect#280]
SocialConnect _should_ keep working almost transparently.

```[tasklist]
### Tasks
- [ ] https://github.com/celo-org/social-connect/issues/289
- [ ] https://github.com/celo-org/celo-blockchain-planning/issues/267
- [ ] https://github.com/celo-org/social-connect/issues/282
- [ ] https://github.com/celo-org/social-connect/issues/284
- [ ] https://github.com/celo-org/social-connect/issues/286
- [ ] https://github.com/celo-org/celo-blockchain-planning/issues/203
- [ ] https://github.com/celo-org/celo-blockchain-planning/issues/204
```

**Comment by mcortesi** [comment]
@alecps @soloseng 

Can you please take a look at the tasks?

My understanding is that there's nothing to do for Alfajores L2. There's only 2 things i imagine make sense:

  * Do a quick test of using ODIS pointing to Danjo, to just check it works. Should basically be the same that checks alfajores but pointin to danjo RPC
  * Double check contracts to see if there's something to change. Or document.
  
  What i see is too many tasks that makes it unclear what this really is.
  
  Am i mistaken?
  
  Also if there are thing that needs to be post-deployment, let's create another isseu for that

**Comment by alecps** [comment]
I agree with @mcortesi , I didn't write any of these tasks and don't understand the reasoning behind most of them. ODIS depends on Forno, so this is really just a task to make sure forno transitions endpoints cleanly

- Ideally, services relying on forno should be able to keep the same URL, and forno will switch to the L2 network when the migration happens so ODIS will not need to do anything
- State will be migrated to the L2, so we don't need to check that contracts are migrated
- No one uses Alfajores ODIS, so we can test this during the alfajores migration

**Nothing changes for ODIS as a result of the L2 migration except for the full node it talks to**

**Comment by alecps** [comment]
@lvpeschke I've removed all the extraneuous tasks from this epic. I'm not sure about the contractkit one. @soloseng can you add context there?

**Comment by lvpeschke** [comment]
Hey all, could the tests on Dango happen ASAP to uncover any potential issues ASAP and decide how to tackle them, if any?

**Comment by alecps** [comment]
@lvpeschke for the tests to happen we need to point Alfajores ODIS to Dango, faucet some Dango accounts (I can ask devops for this) and then just to run our existing e2e tests against that instance. 

This will cover

- https://github.com/celo-org/social-connect/issues/284
- https://github.com/celo-org/social-connect/issues/286

There are some other tickets here that I don't understand 

- https://github.com/celo-org/celo-blockchain-planning/issues/204
- https://github.com/celo-org/celo-blockchain-planning/issues/203
- https://github.com/celo-org/celo-blockchain-planning/issues/267

**Comment by lvpeschke** [comment]
@martinvol do you have more context about the [above](https://github.com/celo-org/social-connect/issues/280#issuecomment-2346706466)?
