### ISSUE TITLE
ODIS Combiner to Prometheus

### ISSUE THREAD

**Issue by alecps** [celo-org/social-connect#64]
- Prometheus metrics are much easier to add / update than log based metrics 
- The signer also uses prometheus metrics, so this will simplify our monitoring / alerting considerably

```[tasklist]
### Tasks
- [ ] https://github.com/celo-org/social-connect/issues/38
- [ ] https://github.com/celo-org/social-connect/issues/65
- [ ] https://github.com/celo-org/social-connect/issues/34
- [ ] https://github.com/celo-org/social-connect/issues/33
- [ ] https://github.com/celo-org/social-connect/issues/32
```
