### ISSUE TITLE
ODIS Combiner to K8s

### ISSUE THREAD

**Issue by alecps** [celo-org/social-connect#65]
- Standardize ODIS operations as the Combiner and Signer will be hosted the same way
- Allow Combiner to use prometheus metrics 
- Possibly solve 500...503 errors returned by Signers that could be caused by Combiner instances being torn down while http connections with signers are open

```[tasklist]
### Tasks
- [ ] https://github.com/celo-org/social-connect/issues/39
- [ ] https://github.com/celo-org/social-connect/issues/38
- [ ] https://github.com/celo-org/social-connect/issues/37
- [ ] https://github.com/celo-org/social-connect/issues/31
```
