### ISSUE TITLE
ODIS MiniPay Launch Follow-up

### ISSUE THREAD

**Issue by alecps** [celo-org/social-connect#66]
Catch all Epic for tasks identified while preparing for the MiniPay launch. Contains sub-epics. Should be split up as needed once MiniPay context is no longer useful for planning.  

```[tasklist]
### Tasks
- [ ] celo-org/social-connect#45
- [x] https://github.com/celo-org/celo-monorepo/issues/10578
- [ ] https://github.com/celo-org/social-connect/issues/64
- [ ] https://github.com/celo-org/social-connect/issues/63
- [ ] https://github.com/celo-org/social-connect/issues/40
- [x] https://github.com/celo-org/celo-monorepo/issues/10600
- [ ] https://github.com/celo-org/social-connect/issues/62
- [ ] https://github.com/celo-org/social-connect/issues/61
- [ ] https://github.com/celo-org/social-connect/issues/60
- [ ] https://github.com/celo-org/social-connect/issues/59
- [ ] https://github.com/celo-org/social-connect/issues/58
- [ ] https://github.com/celo-org/social-connect/issues/57
- [ ] https://github.com/celo-org/social-connect/issues/56
- [ ] https://github.com/celo-org/social-connect/issues/55
- [ ] https://github.com/celo-org/celo-monorepo/issues/10589
- [ ] https://github.com/celo-org/social-connect/issues/43
- [ ] https://github.com/celo-org/social-connect/issues/42
- [ ] https://github.com/celo-org/social-connect/issues/41
- [ ] https://github.com/celo-org/social-connect/issues/67
- [ ] https://github.com/celo-org/social-connect/issues/68
- [ ] https://github.com/celo-org/social-connect/issues/36
- [ ] https://github.com/celo-org/social-connect/issues/30
```
